John conroy/additional dataset fields
hubmapconsortium/search-api pull request #742
Opened 2024-01-18 19:37 UTC by john-conroy

2024-01-18 23:08 UTC, lchoy requested changes

2024-01-19 15:11 UTC, john-conroy commented on src/hubmap_translation/addl_index_transformations/portal/add_assay_details.py
> +        if pipeline := re.search("(?<=\\[)[^][]*(?=])", doc['dataset_type']):
Is the concern that `dataset_type` might not exist in the doc? We do check for the existence in an above line, but I've made the changes to use `.get()`.

2024-01-19 15:51 UTC, lchoy approved these changes

2024-01-19 17:19 UTC, yuanzhou approved these changes

2024-01-19 17:19 UTC, merged